# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a2
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aiochris_oag.api.schema_api import SchemaApi


class TestSchemaApi(unittest.IsolatedAsyncioTestCase):
    """SchemaApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SchemaApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_schema_retrieve(self) -> None:
        """Test case for schema_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
