# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a1
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aiochris_oag.api.default_api import DefaultApi


class TestDefaultApi(unittest.IsolatedAsyncioTestCase):
    """DefaultApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DefaultApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_root_destroy(self) -> None:
        """Test case for root_destroy

        """
        pass

    async def test_root_list(self) -> None:
        """Test case for root_list

        """
        pass

    async def test_root_retrieve(self) -> None:
        """Test case for root_retrieve

        """
        pass

    async def test_root_update(self) -> None:
        """Test case for root_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
