# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a2
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chris_oag.api.pacs_api import PacsApi


class TestPacsApi(unittest.TestCase):
    """PacsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PacsApi()

    def tearDown(self) -> None:
        pass

    def test_all_pacs_query_list(self) -> None:
        """Test case for all_pacs_query_list

        """
        pass

    def test_all_pacs_series_list(self) -> None:
        """Test case for all_pacs_series_list

        """
        pass

    def test_pacs_files_list(self) -> None:
        """Test case for pacs_files_list

        """
        pass

    def test_pacs_files_retrieve(self) -> None:
        """Test case for pacs_files_retrieve

        """
        pass

    def test_pacs_files_retrieve_0(self) -> None:
        """Test case for pacs_files_retrieve_0

        """
        pass

    def test_pacs_files_search_list(self) -> None:
        """Test case for pacs_files_search_list

        """
        pass

    def test_pacs_list(self) -> None:
        """Test case for pacs_list

        """
        pass

    def test_pacs_queries_create(self) -> None:
        """Test case for pacs_queries_create

        """
        pass

    def test_pacs_queries_destroy(self) -> None:
        """Test case for pacs_queries_destroy

        """
        pass

    def test_pacs_queries_retrieve(self) -> None:
        """Test case for pacs_queries_retrieve

        """
        pass

    def test_pacs_queries_retrieves_create(self) -> None:
        """Test case for pacs_queries_retrieves_create

        """
        pass

    def test_pacs_queries_retrieves_destroy(self) -> None:
        """Test case for pacs_queries_retrieves_destroy

        """
        pass

    def test_pacs_queries_retrieves_list(self) -> None:
        """Test case for pacs_queries_retrieves_list

        """
        pass

    def test_pacs_queries_retrieves_retrieve(self) -> None:
        """Test case for pacs_queries_retrieves_retrieve

        """
        pass

    def test_pacs_queries_retrieves_search_list(self) -> None:
        """Test case for pacs_queries_retrieves_search_list

        """
        pass

    def test_pacs_queries_search_list(self) -> None:
        """Test case for pacs_queries_search_list

        """
        pass

    def test_pacs_queries_update(self) -> None:
        """Test case for pacs_queries_update

        """
        pass

    def test_pacs_query_list(self) -> None:
        """Test case for pacs_query_list

        """
        pass

    def test_pacs_retrieve(self) -> None:
        """Test case for pacs_retrieve

        """
        pass

    def test_pacs_search_list(self) -> None:
        """Test case for pacs_search_list

        """
        pass

    def test_pacs_series_create(self) -> None:
        """Test case for pacs_series_create

        """
        pass

    def test_pacs_series_destroy(self) -> None:
        """Test case for pacs_series_destroy

        """
        pass

    def test_pacs_series_list(self) -> None:
        """Test case for pacs_series_list

        """
        pass

    def test_pacs_series_retrieve(self) -> None:
        """Test case for pacs_series_retrieve

        """
        pass

    def test_pacs_series_search_list(self) -> None:
        """Test case for pacs_series_search_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
