# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a1
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chris_oag.models.pacs_query_status import PacsQueryStatus

class TestPacsQueryStatus(unittest.TestCase):
    """PacsQueryStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPacsQueryStatus(self):
        """Test PacsQueryStatus"""
        # inst = PacsQueryStatus()

if __name__ == '__main__':
    unittest.main()
