# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a1
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chris_oag.models.paginated_pacs_query_list import PaginatedPACSQueryList

class TestPaginatedPACSQueryList(unittest.TestCase):
    """PaginatedPACSQueryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedPACSQueryList:
        """Test PaginatedPACSQueryList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedPACSQueryList`
        """
        model = PaginatedPACSQueryList()
        if include_optional:
            return PaginatedPACSQueryList(
                count = 123,
                next = 'http://api.example.org/accounts/?offset=400&limit=100',
                previous = 'http://api.example.org/accounts/?offset=200&limit=100',
                results = [
                    chris_oag.models.pacs_query.PACSQuery(
                        url = '', 
                        id = 56, 
                        creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        title = '', 
                        query = null, 
                        description = '', 
                        status = null, 
                        pacs_identifier = '', 
                        owner_username = '', 
                        execute = True, 
                        result = '', 
                        retrieve_list = '', )
                    ]
            )
        else:
            return PaginatedPACSQueryList(
                count = 123,
                results = [
                    chris_oag.models.pacs_query.PACSQuery(
                        url = '', 
                        id = 56, 
                        creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        title = '', 
                        query = null, 
                        description = '', 
                        status = null, 
                        pacs_identifier = '', 
                        owner_username = '', 
                        execute = True, 
                        result = '', 
                        retrieve_list = '', )
                    ],
        )
        """

    def testPaginatedPACSQueryList(self):
        """Test PaginatedPACSQueryList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
