# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a1
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chris_oag.models.pacs_query import PACSQuery

class TestPACSQuery(unittest.TestCase):
    """PACSQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PACSQuery:
        """Test PACSQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PACSQuery`
        """
        model = PACSQuery()
        if include_optional:
            return PACSQuery(
                url = '',
                id = 56,
                creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                title = '',
                query = None,
                description = '',
                status = 'created',
                pacs_identifier = '',
                owner_username = '',
                execute = True,
                result = '',
                retrieve_list = ''
            )
        else:
            return PACSQuery(
                url = '',
                id = 56,
                creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'created',
                pacs_identifier = '',
                owner_username = '',
                result = '',
                retrieve_list = '',
        )
        """

    def testPACSQuery(self):
        """Test PACSQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
