generate-batch: sync-versions
    podman run --rm --userns=keep-id:uid=100100,gid=100100 -u 100100:100100 \
        -v "$(pwd):/share" -w /share \
        docker.io/openapitools/openapi-generator-cli:v7.9.0 \
        batch --clean --fail-fast --root-dir /share --includes-base-dir /share/includes \
        configs/*.yaml

sync-versions:
    just write-version-file version.yaml         packageVersion  $(just get-version)
    just write-version-file version_npm.yaml     npmVersion      $(just get-version)
    just write-version-file version_pep440.yaml  packageVersion  $(just get-version-pep440)

write-version-file file key value:
    @echo '# This file was automatically generated by `just`. Do not edit it manually.' > includes/{{file}}
    @echo "{{key}}: '{{value}}'" >> includes/{{file}}

get-version-pep440:
    @./semver2pep440.sh < version.txt

get-version:
    @cat version.txt

