# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a1
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ComputeResource(BaseModel):
    """
    ComputeResource
    """ # noqa: E501
    url: StrictStr
    id: StrictInt
    creation_date: datetime
    modification_date: datetime
    name: Annotated[str, Field(strict=True, max_length=100)]
    compute_url: Annotated[str, Field(strict=True, max_length=300)]
    compute_auth_url: Optional[Annotated[str, Field(strict=True, max_length=350)]] = None
    compute_innetwork: StrictBool
    compute_requires_copy_job: StrictBool
    compute_requires_upload_job: StrictBool
    description: Optional[Annotated[str, Field(strict=True, max_length=600)]] = None
    max_job_exec_seconds: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    __properties: ClassVar[List[str]] = ["url", "id", "creation_date", "modification_date", "name", "compute_url", "compute_auth_url", "compute_innetwork", "compute_requires_copy_job", "compute_requires_upload_job", "description", "max_job_exec_seconds"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComputeResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "url",
            "id",
            "creation_date",
            "modification_date",
            "compute_innetwork",
            "compute_requires_copy_job",
            "compute_requires_upload_job",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComputeResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "id": obj.get("id"),
            "creation_date": obj.get("creation_date"),
            "modification_date": obj.get("modification_date"),
            "name": obj.get("name"),
            "compute_url": obj.get("compute_url"),
            "compute_auth_url": obj.get("compute_auth_url"),
            "compute_innetwork": obj.get("compute_innetwork"),
            "compute_requires_copy_job": obj.get("compute_requires_copy_job"),
            "compute_requires_upload_job": obj.get("compute_requires_upload_job"),
            "description": obj.get("description"),
            "max_job_exec_seconds": obj.get("max_job_exec_seconds")
        })
        return _obj


