# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a2
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from chris_oag.models.deletion_status_enum import DeletionStatusEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PACSSeries(BaseModel):
    """
    PACSSeries
    """ # noqa: E501
    url: StrictStr
    id: StrictInt
    creation_date: datetime
    folder_path: StrictStr
    patient_id: Annotated[str, Field(strict=True, max_length=100)] = Field(alias="PatientID")
    patient_name: Optional[Annotated[str, Field(strict=True, max_length=150)]] = Field(default=None, alias="PatientName")
    patient_birth_date: Optional[date] = Field(default=None, alias="PatientBirthDate")
    patient_age: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = Field(default=None, alias="PatientAge")
    patient_sex: Optional[StrictStr] = Field(default=None, alias="PatientSex")
    study_date: date = Field(alias="StudyDate")
    accession_number: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, alias="AccessionNumber")
    modality: Optional[Annotated[str, Field(strict=True, max_length=15)]] = Field(default=None, alias="Modality")
    protocol_name: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, alias="ProtocolName")
    study_instance_uid: Annotated[str, Field(strict=True, max_length=100)] = Field(alias="StudyInstanceUID")
    study_description: Optional[Annotated[str, Field(strict=True, max_length=400)]] = Field(default=None, alias="StudyDescription")
    series_instance_uid: Annotated[str, Field(strict=True, max_length=100)] = Field(alias="SeriesInstanceUID")
    series_description: Optional[Annotated[str, Field(strict=True, max_length=400)]] = Field(default=None, alias="SeriesDescription")
    pacs_identifier: StrictStr
    deletion_status: Optional[DeletionStatusEnum] = None
    deletion_requested_at: Optional[datetime] = None
    deletion_error: Optional[StrictStr] = None
    folder: StrictStr
    __properties: ClassVar[List[str]] = ["url", "id", "creation_date", "folder_path", "PatientID", "PatientName", "PatientBirthDate", "PatientAge", "PatientSex", "StudyDate", "AccessionNumber", "Modality", "ProtocolName", "StudyInstanceUID", "StudyDescription", "SeriesInstanceUID", "SeriesDescription", "pacs_identifier", "deletion_status", "deletion_requested_at", "deletion_error", "folder"]

    @field_validator('patient_sex')
    def patient_sex_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['M', 'F', 'O', '']):
            raise ValueError("must be one of enum values ('M', 'F', 'O', '')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PACSSeries from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "url",
            "id",
            "creation_date",
            "folder_path",
            "pacs_identifier",
            "folder",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if patient_birth_date (nullable) is None
        # and model_fields_set contains the field
        if self.patient_birth_date is None and "patient_birth_date" in self.model_fields_set:
            _dict['PatientBirthDate'] = None

        # set to None if patient_age (nullable) is None
        # and model_fields_set contains the field
        if self.patient_age is None and "patient_age" in self.model_fields_set:
            _dict['PatientAge'] = None

        # set to None if deletion_requested_at (nullable) is None
        # and model_fields_set contains the field
        if self.deletion_requested_at is None and "deletion_requested_at" in self.model_fields_set:
            _dict['deletion_requested_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PACSSeries from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "id": obj.get("id"),
            "creation_date": obj.get("creation_date"),
            "folder_path": obj.get("folder_path"),
            "PatientID": obj.get("PatientID"),
            "PatientName": obj.get("PatientName"),
            "PatientBirthDate": obj.get("PatientBirthDate"),
            "PatientAge": obj.get("PatientAge"),
            "PatientSex": obj.get("PatientSex"),
            "StudyDate": obj.get("StudyDate"),
            "AccessionNumber": obj.get("AccessionNumber"),
            "Modality": obj.get("Modality"),
            "ProtocolName": obj.get("ProtocolName"),
            "StudyInstanceUID": obj.get("StudyInstanceUID"),
            "StudyDescription": obj.get("StudyDescription"),
            "SeriesInstanceUID": obj.get("SeriesInstanceUID"),
            "SeriesDescription": obj.get("SeriesDescription"),
            "pacs_identifier": obj.get("pacs_identifier"),
            "deletion_status": obj.get("deletion_status"),
            "deletion_requested_at": obj.get("deletion_requested_at"),
            "deletion_error": obj.get("deletion_error"),
            "folder": obj.get("folder")
        })
        return _obj


