# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a2
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PipelineSourceFile(BaseModel):
    """
    A superclass for serializers of ``ChrisFile`` or similar.
    """ # noqa: E501
    url: StrictStr
    id: StrictInt
    creation_date: datetime
    fname: StrictStr
    fsize: StrictInt = Field(description="Get the size of the file in bytes.")
    public: Optional[StrictBool] = None
    ftype: Optional[StrictStr]
    uploader_username: Optional[StrictStr] = Field(description="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.")
    owner_username: StrictStr = Field(description="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.")
    pipeline_id: Optional[StrictInt]
    pipeline_name: Optional[StrictStr]
    file_resource: StrictStr = Field(description="Custom method to get the hyperlink to the actual file resource.")
    parent_folder: StrictStr
    owner: StrictStr
    __properties: ClassVar[List[str]] = ["url", "id", "creation_date", "fname", "fsize", "public", "ftype", "uploader_username", "owner_username", "pipeline_id", "pipeline_name", "file_resource", "parent_folder", "owner"]

    @field_validator('ftype')
    def ftype_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['yaml', 'json', '']):
            raise ValueError("must be one of enum values ('yaml', 'json', '')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PipelineSourceFile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "url",
            "id",
            "creation_date",
            "fsize",
            "ftype",
            "uploader_username",
            "owner_username",
            "pipeline_id",
            "pipeline_name",
            "file_resource",
            "parent_folder",
            "owner",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if ftype (nullable) is None
        # and model_fields_set contains the field
        if self.ftype is None and "ftype" in self.model_fields_set:
            _dict['ftype'] = None

        # set to None if uploader_username (nullable) is None
        # and model_fields_set contains the field
        if self.uploader_username is None and "uploader_username" in self.model_fields_set:
            _dict['uploader_username'] = None

        # set to None if pipeline_id (nullable) is None
        # and model_fields_set contains the field
        if self.pipeline_id is None and "pipeline_id" in self.model_fields_set:
            _dict['pipeline_id'] = None

        # set to None if pipeline_name (nullable) is None
        # and model_fields_set contains the field
        if self.pipeline_name is None and "pipeline_name" in self.model_fields_set:
            _dict['pipeline_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PipelineSourceFile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "id": obj.get("id"),
            "creation_date": obj.get("creation_date"),
            "fname": obj.get("fname"),
            "fsize": obj.get("fsize"),
            "public": obj.get("public"),
            "ftype": obj.get("ftype"),
            "uploader_username": obj.get("uploader_username"),
            "owner_username": obj.get("owner_username"),
            "pipeline_id": obj.get("pipeline_id"),
            "pipeline_name": obj.get("pipeline_name"),
            "file_resource": obj.get("file_resource"),
            "parent_folder": obj.get("parent_folder"),
            "owner": obj.get("owner")
        })
        return _obj


