# coding: utf-8

# flake8: noqa

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a2
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.3"

# Define package exports
__all__ = [
    "AuthTokenApi",
    "ChrisAdminApi",
    "ChrisinstanceApi",
    "CommentsApi",
    "ComputeresourcesApi",
    "DefaultApi",
    "DownloadtokensApi",
    "FilebrowserApi",
    "GrouppermissionsApi",
    "GroupsApi",
    "NoteApi",
    "PacsApi",
    "PipelinesApi",
    "PlugininstancesApi",
    "PluginsApi",
    "PublicfeedsApi",
    "SchemaApi",
    "SearchApi",
    "TaggingsApi",
    "TagsApi",
    "UserfilesApi",
    "UserpermissionsApi",
    "UsersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AuthToken",
    "AuthTokenRequest",
    "BlankEnum",
    "BoolParameter",
    "ChrisInstance",
    "Comment",
    "CommentRequest",
    "ComputeResource",
    "ComputeResourceRequest",
    "DefaultPipingBoolParameter",
    "DefaultPipingBoolParameterRequest",
    "DefaultPipingFloatParameter",
    "DefaultPipingFloatParameterRequest",
    "DefaultPipingIntParameter",
    "DefaultPipingIntParameterRequest",
    "DefaultPipingStrParameter",
    "DefaultPipingStrParameterRequest",
    "DeletionStatusEnum",
    "Feed",
    "FeedGroupPermission",
    "FeedGroupPermissionRequest",
    "FeedRequest",
    "FeedUserPermission",
    "FeedUserPermissionRequest",
    "FileBrowserFile",
    "FileBrowserFileGroupPermission",
    "FileBrowserFileGroupPermissionRequest",
    "FileBrowserFileRequest",
    "FileBrowserFileUserPermission",
    "FileBrowserFileUserPermissionRequest",
    "FileBrowserFolder",
    "FileBrowserFolderGroupPermission",
    "FileBrowserFolderGroupPermissionRequest",
    "FileBrowserFolderRequest",
    "FileBrowserFolderUserPermission",
    "FileBrowserFolderUserPermissionRequest",
    "FileBrowserLinkFile",
    "FileBrowserLinkFileGroupPermission",
    "FileBrowserLinkFileGroupPermissionRequest",
    "FileBrowserLinkFileRequest",
    "FileBrowserLinkFileUserPermission",
    "FileBrowserLinkFileUserPermissionRequest",
    "FileDownloadToken",
    "FileDownloadTokenRequest",
    "FloatParameter",
    "FtypeEnum",
    "GenericDefaultPipingParameter",
    "GenericDefaultPipingParameterValue",
    "GenericParameter",
    "Group",
    "GroupRequest",
    "GroupUser",
    "GroupUserRequest",
    "IntParameter",
    "Note",
    "NoteRequest",
    "PACS",
    "PACSFile",
    "PACSQuery",
    "PACSQueryRequest",
    "PACSRetrieve",
    "PACSSeries",
    "PACSSeriesRequest",
    "PacsQueryStatus",
    "PaginatedCommentList",
    "PaginatedComputeResourceList",
    "PaginatedFeedGroupPermissionList",
    "PaginatedFeedList",
    "PaginatedFeedUserPermissionList",
    "PaginatedFileBrowserFileGroupPermissionList",
    "PaginatedFileBrowserFileList",
    "PaginatedFileBrowserFileUserPermissionList",
    "PaginatedFileBrowserFolderGroupPermissionList",
    "PaginatedFileBrowserFolderList",
    "PaginatedFileBrowserFolderUserPermissionList",
    "PaginatedFileBrowserLinkFileGroupPermissionList",
    "PaginatedFileBrowserLinkFileList",
    "PaginatedFileBrowserLinkFileUserPermissionList",
    "PaginatedFileDownloadTokenList",
    "PaginatedGenericDefaultPipingParameterList",
    "PaginatedGenericParameterList",
    "PaginatedGroupList",
    "PaginatedGroupUserList",
    "PaginatedPACSFileList",
    "PaginatedPACSList",
    "PaginatedPACSQueryList",
    "PaginatedPACSRetrieveList",
    "PaginatedPACSSeriesList",
    "PaginatedPartialPluginInstanceList",
    "PaginatedPipelineList",
    "PaginatedPipelineSourceFileList",
    "PaginatedPluginAdminList",
    "PaginatedPluginInstanceList",
    "PaginatedPluginInstanceSplitList",
    "PaginatedPluginList",
    "PaginatedPluginMetaList",
    "PaginatedPluginParameterList",
    "PaginatedPluginPipingList",
    "PaginatedTagList",
    "PaginatedTaggingList",
    "PaginatedUserFileList",
    "PaginatedUserList",
    "PaginatedWorkflowList",
    "PartialPluginInstance",
    "PathParameter",
    "PatientSexEnum",
    "PermissionEnum",
    "Pipeline",
    "PipelineCustomJson",
    "PipelineRequest",
    "PipelineSourceFile",
    "PipelineSourceFileRequest",
    "Plugin",
    "PluginAdmin",
    "PluginAdminRequest",
    "PluginInstance",
    "PluginInstanceRequest",
    "PluginInstanceSplit",
    "PluginInstanceSplitRequest",
    "PluginInstanceStatus",
    "PluginMeta",
    "PluginParameter",
    "PluginParameterDefault",
    "PluginParameterType",
    "PluginPiping",
    "PluginType",
    "StrParameter",
    "Tag",
    "TagRequest",
    "Tagging",
    "UnextpathParameter",
    "User",
    "UserFile",
    "UserFileRequest",
    "UserRequest",
    "Workflow",
    "WorkflowRequest",
]

# import apis into sdk package
from chris_oag.api.auth_token_api import AuthTokenApi as AuthTokenApi
from chris_oag.api.chris_admin_api import ChrisAdminApi as ChrisAdminApi
from chris_oag.api.chrisinstance_api import ChrisinstanceApi as ChrisinstanceApi
from chris_oag.api.comments_api import CommentsApi as CommentsApi
from chris_oag.api.computeresources_api import ComputeresourcesApi as ComputeresourcesApi
from chris_oag.api.default_api import DefaultApi as DefaultApi
from chris_oag.api.downloadtokens_api import DownloadtokensApi as DownloadtokensApi
from chris_oag.api.filebrowser_api import FilebrowserApi as FilebrowserApi
from chris_oag.api.grouppermissions_api import GrouppermissionsApi as GrouppermissionsApi
from chris_oag.api.groups_api import GroupsApi as GroupsApi
from chris_oag.api.note_api import NoteApi as NoteApi
from chris_oag.api.pacs_api import PacsApi as PacsApi
from chris_oag.api.pipelines_api import PipelinesApi as PipelinesApi
from chris_oag.api.plugininstances_api import PlugininstancesApi as PlugininstancesApi
from chris_oag.api.plugins_api import PluginsApi as PluginsApi
from chris_oag.api.publicfeeds_api import PublicfeedsApi as PublicfeedsApi
from chris_oag.api.schema_api import SchemaApi as SchemaApi
from chris_oag.api.search_api import SearchApi as SearchApi
from chris_oag.api.taggings_api import TaggingsApi as TaggingsApi
from chris_oag.api.tags_api import TagsApi as TagsApi
from chris_oag.api.userfiles_api import UserfilesApi as UserfilesApi
from chris_oag.api.userpermissions_api import UserpermissionsApi as UserpermissionsApi
from chris_oag.api.users_api import UsersApi as UsersApi

# import ApiClient
from chris_oag.api_response import ApiResponse as ApiResponse
from chris_oag.api_client import ApiClient as ApiClient
from chris_oag.configuration import Configuration as Configuration
from chris_oag.exceptions import OpenApiException as OpenApiException
from chris_oag.exceptions import ApiTypeError as ApiTypeError
from chris_oag.exceptions import ApiValueError as ApiValueError
from chris_oag.exceptions import ApiKeyError as ApiKeyError
from chris_oag.exceptions import ApiAttributeError as ApiAttributeError
from chris_oag.exceptions import ApiException as ApiException

# import models into sdk package
from chris_oag.models.auth_token import AuthToken as AuthToken
from chris_oag.models.auth_token_request import AuthTokenRequest as AuthTokenRequest
from chris_oag.models.blank_enum import BlankEnum as BlankEnum
from chris_oag.models.bool_parameter import BoolParameter as BoolParameter
from chris_oag.models.chris_instance import ChrisInstance as ChrisInstance
from chris_oag.models.comment import Comment as Comment
from chris_oag.models.comment_request import CommentRequest as CommentRequest
from chris_oag.models.compute_resource import ComputeResource as ComputeResource
from chris_oag.models.compute_resource_request import ComputeResourceRequest as ComputeResourceRequest
from chris_oag.models.default_piping_bool_parameter import DefaultPipingBoolParameter as DefaultPipingBoolParameter
from chris_oag.models.default_piping_bool_parameter_request import DefaultPipingBoolParameterRequest as DefaultPipingBoolParameterRequest
from chris_oag.models.default_piping_float_parameter import DefaultPipingFloatParameter as DefaultPipingFloatParameter
from chris_oag.models.default_piping_float_parameter_request import DefaultPipingFloatParameterRequest as DefaultPipingFloatParameterRequest
from chris_oag.models.default_piping_int_parameter import DefaultPipingIntParameter as DefaultPipingIntParameter
from chris_oag.models.default_piping_int_parameter_request import DefaultPipingIntParameterRequest as DefaultPipingIntParameterRequest
from chris_oag.models.default_piping_str_parameter import DefaultPipingStrParameter as DefaultPipingStrParameter
from chris_oag.models.default_piping_str_parameter_request import DefaultPipingStrParameterRequest as DefaultPipingStrParameterRequest
from chris_oag.models.deletion_status_enum import DeletionStatusEnum as DeletionStatusEnum
from chris_oag.models.feed import Feed as Feed
from chris_oag.models.feed_group_permission import FeedGroupPermission as FeedGroupPermission
from chris_oag.models.feed_group_permission_request import FeedGroupPermissionRequest as FeedGroupPermissionRequest
from chris_oag.models.feed_request import FeedRequest as FeedRequest
from chris_oag.models.feed_user_permission import FeedUserPermission as FeedUserPermission
from chris_oag.models.feed_user_permission_request import FeedUserPermissionRequest as FeedUserPermissionRequest
from chris_oag.models.file_browser_file import FileBrowserFile as FileBrowserFile
from chris_oag.models.file_browser_file_group_permission import FileBrowserFileGroupPermission as FileBrowserFileGroupPermission
from chris_oag.models.file_browser_file_group_permission_request import FileBrowserFileGroupPermissionRequest as FileBrowserFileGroupPermissionRequest
from chris_oag.models.file_browser_file_request import FileBrowserFileRequest as FileBrowserFileRequest
from chris_oag.models.file_browser_file_user_permission import FileBrowserFileUserPermission as FileBrowserFileUserPermission
from chris_oag.models.file_browser_file_user_permission_request import FileBrowserFileUserPermissionRequest as FileBrowserFileUserPermissionRequest
from chris_oag.models.file_browser_folder import FileBrowserFolder as FileBrowserFolder
from chris_oag.models.file_browser_folder_group_permission import FileBrowserFolderGroupPermission as FileBrowserFolderGroupPermission
from chris_oag.models.file_browser_folder_group_permission_request import FileBrowserFolderGroupPermissionRequest as FileBrowserFolderGroupPermissionRequest
from chris_oag.models.file_browser_folder_request import FileBrowserFolderRequest as FileBrowserFolderRequest
from chris_oag.models.file_browser_folder_user_permission import FileBrowserFolderUserPermission as FileBrowserFolderUserPermission
from chris_oag.models.file_browser_folder_user_permission_request import FileBrowserFolderUserPermissionRequest as FileBrowserFolderUserPermissionRequest
from chris_oag.models.file_browser_link_file import FileBrowserLinkFile as FileBrowserLinkFile
from chris_oag.models.file_browser_link_file_group_permission import FileBrowserLinkFileGroupPermission as FileBrowserLinkFileGroupPermission
from chris_oag.models.file_browser_link_file_group_permission_request import FileBrowserLinkFileGroupPermissionRequest as FileBrowserLinkFileGroupPermissionRequest
from chris_oag.models.file_browser_link_file_request import FileBrowserLinkFileRequest as FileBrowserLinkFileRequest
from chris_oag.models.file_browser_link_file_user_permission import FileBrowserLinkFileUserPermission as FileBrowserLinkFileUserPermission
from chris_oag.models.file_browser_link_file_user_permission_request import FileBrowserLinkFileUserPermissionRequest as FileBrowserLinkFileUserPermissionRequest
from chris_oag.models.file_download_token import FileDownloadToken as FileDownloadToken
from chris_oag.models.file_download_token_request import FileDownloadTokenRequest as FileDownloadTokenRequest
from chris_oag.models.float_parameter import FloatParameter as FloatParameter
from chris_oag.models.ftype_enum import FtypeEnum as FtypeEnum
from chris_oag.models.generic_default_piping_parameter import GenericDefaultPipingParameter as GenericDefaultPipingParameter
from chris_oag.models.generic_default_piping_parameter_value import GenericDefaultPipingParameterValue as GenericDefaultPipingParameterValue
from chris_oag.models.generic_parameter import GenericParameter as GenericParameter
from chris_oag.models.group import Group as Group
from chris_oag.models.group_request import GroupRequest as GroupRequest
from chris_oag.models.group_user import GroupUser as GroupUser
from chris_oag.models.group_user_request import GroupUserRequest as GroupUserRequest
from chris_oag.models.int_parameter import IntParameter as IntParameter
from chris_oag.models.note import Note as Note
from chris_oag.models.note_request import NoteRequest as NoteRequest
from chris_oag.models.pacs import PACS as PACS
from chris_oag.models.pacs_file import PACSFile as PACSFile
from chris_oag.models.pacs_query import PACSQuery as PACSQuery
from chris_oag.models.pacs_query_request import PACSQueryRequest as PACSQueryRequest
from chris_oag.models.pacs_retrieve import PACSRetrieve as PACSRetrieve
from chris_oag.models.pacs_series import PACSSeries as PACSSeries
from chris_oag.models.pacs_series_request import PACSSeriesRequest as PACSSeriesRequest
from chris_oag.models.pacs_query_status import PacsQueryStatus as PacsQueryStatus
from chris_oag.models.paginated_comment_list import PaginatedCommentList as PaginatedCommentList
from chris_oag.models.paginated_compute_resource_list import PaginatedComputeResourceList as PaginatedComputeResourceList
from chris_oag.models.paginated_feed_group_permission_list import PaginatedFeedGroupPermissionList as PaginatedFeedGroupPermissionList
from chris_oag.models.paginated_feed_list import PaginatedFeedList as PaginatedFeedList
from chris_oag.models.paginated_feed_user_permission_list import PaginatedFeedUserPermissionList as PaginatedFeedUserPermissionList
from chris_oag.models.paginated_file_browser_file_group_permission_list import PaginatedFileBrowserFileGroupPermissionList as PaginatedFileBrowserFileGroupPermissionList
from chris_oag.models.paginated_file_browser_file_list import PaginatedFileBrowserFileList as PaginatedFileBrowserFileList
from chris_oag.models.paginated_file_browser_file_user_permission_list import PaginatedFileBrowserFileUserPermissionList as PaginatedFileBrowserFileUserPermissionList
from chris_oag.models.paginated_file_browser_folder_group_permission_list import PaginatedFileBrowserFolderGroupPermissionList as PaginatedFileBrowserFolderGroupPermissionList
from chris_oag.models.paginated_file_browser_folder_list import PaginatedFileBrowserFolderList as PaginatedFileBrowserFolderList
from chris_oag.models.paginated_file_browser_folder_user_permission_list import PaginatedFileBrowserFolderUserPermissionList as PaginatedFileBrowserFolderUserPermissionList
from chris_oag.models.paginated_file_browser_link_file_group_permission_list import PaginatedFileBrowserLinkFileGroupPermissionList as PaginatedFileBrowserLinkFileGroupPermissionList
from chris_oag.models.paginated_file_browser_link_file_list import PaginatedFileBrowserLinkFileList as PaginatedFileBrowserLinkFileList
from chris_oag.models.paginated_file_browser_link_file_user_permission_list import PaginatedFileBrowserLinkFileUserPermissionList as PaginatedFileBrowserLinkFileUserPermissionList
from chris_oag.models.paginated_file_download_token_list import PaginatedFileDownloadTokenList as PaginatedFileDownloadTokenList
from chris_oag.models.paginated_generic_default_piping_parameter_list import PaginatedGenericDefaultPipingParameterList as PaginatedGenericDefaultPipingParameterList
from chris_oag.models.paginated_generic_parameter_list import PaginatedGenericParameterList as PaginatedGenericParameterList
from chris_oag.models.paginated_group_list import PaginatedGroupList as PaginatedGroupList
from chris_oag.models.paginated_group_user_list import PaginatedGroupUserList as PaginatedGroupUserList
from chris_oag.models.paginated_pacs_file_list import PaginatedPACSFileList as PaginatedPACSFileList
from chris_oag.models.paginated_pacs_list import PaginatedPACSList as PaginatedPACSList
from chris_oag.models.paginated_pacs_query_list import PaginatedPACSQueryList as PaginatedPACSQueryList
from chris_oag.models.paginated_pacs_retrieve_list import PaginatedPACSRetrieveList as PaginatedPACSRetrieveList
from chris_oag.models.paginated_pacs_series_list import PaginatedPACSSeriesList as PaginatedPACSSeriesList
from chris_oag.models.paginated_partial_plugin_instance_list import PaginatedPartialPluginInstanceList as PaginatedPartialPluginInstanceList
from chris_oag.models.paginated_pipeline_list import PaginatedPipelineList as PaginatedPipelineList
from chris_oag.models.paginated_pipeline_source_file_list import PaginatedPipelineSourceFileList as PaginatedPipelineSourceFileList
from chris_oag.models.paginated_plugin_admin_list import PaginatedPluginAdminList as PaginatedPluginAdminList
from chris_oag.models.paginated_plugin_instance_list import PaginatedPluginInstanceList as PaginatedPluginInstanceList
from chris_oag.models.paginated_plugin_instance_split_list import PaginatedPluginInstanceSplitList as PaginatedPluginInstanceSplitList
from chris_oag.models.paginated_plugin_list import PaginatedPluginList as PaginatedPluginList
from chris_oag.models.paginated_plugin_meta_list import PaginatedPluginMetaList as PaginatedPluginMetaList
from chris_oag.models.paginated_plugin_parameter_list import PaginatedPluginParameterList as PaginatedPluginParameterList
from chris_oag.models.paginated_plugin_piping_list import PaginatedPluginPipingList as PaginatedPluginPipingList
from chris_oag.models.paginated_tag_list import PaginatedTagList as PaginatedTagList
from chris_oag.models.paginated_tagging_list import PaginatedTaggingList as PaginatedTaggingList
from chris_oag.models.paginated_user_file_list import PaginatedUserFileList as PaginatedUserFileList
from chris_oag.models.paginated_user_list import PaginatedUserList as PaginatedUserList
from chris_oag.models.paginated_workflow_list import PaginatedWorkflowList as PaginatedWorkflowList
from chris_oag.models.partial_plugin_instance import PartialPluginInstance as PartialPluginInstance
from chris_oag.models.path_parameter import PathParameter as PathParameter
from chris_oag.models.patient_sex_enum import PatientSexEnum as PatientSexEnum
from chris_oag.models.permission_enum import PermissionEnum as PermissionEnum
from chris_oag.models.pipeline import Pipeline as Pipeline
from chris_oag.models.pipeline_custom_json import PipelineCustomJson as PipelineCustomJson
from chris_oag.models.pipeline_request import PipelineRequest as PipelineRequest
from chris_oag.models.pipeline_source_file import PipelineSourceFile as PipelineSourceFile
from chris_oag.models.pipeline_source_file_request import PipelineSourceFileRequest as PipelineSourceFileRequest
from chris_oag.models.plugin import Plugin as Plugin
from chris_oag.models.plugin_admin import PluginAdmin as PluginAdmin
from chris_oag.models.plugin_admin_request import PluginAdminRequest as PluginAdminRequest
from chris_oag.models.plugin_instance import PluginInstance as PluginInstance
from chris_oag.models.plugin_instance_request import PluginInstanceRequest as PluginInstanceRequest
from chris_oag.models.plugin_instance_split import PluginInstanceSplit as PluginInstanceSplit
from chris_oag.models.plugin_instance_split_request import PluginInstanceSplitRequest as PluginInstanceSplitRequest
from chris_oag.models.plugin_instance_status import PluginInstanceStatus as PluginInstanceStatus
from chris_oag.models.plugin_meta import PluginMeta as PluginMeta
from chris_oag.models.plugin_parameter import PluginParameter as PluginParameter
from chris_oag.models.plugin_parameter_default import PluginParameterDefault as PluginParameterDefault
from chris_oag.models.plugin_parameter_type import PluginParameterType as PluginParameterType
from chris_oag.models.plugin_piping import PluginPiping as PluginPiping
from chris_oag.models.plugin_type import PluginType as PluginType
from chris_oag.models.str_parameter import StrParameter as StrParameter
from chris_oag.models.tag import Tag as Tag
from chris_oag.models.tag_request import TagRequest as TagRequest
from chris_oag.models.tagging import Tagging as Tagging
from chris_oag.models.unextpath_parameter import UnextpathParameter as UnextpathParameter
from chris_oag.models.user import User as User
from chris_oag.models.user_file import UserFile as UserFile
from chris_oag.models.user_file_request import UserFileRequest as UserFileRequest
from chris_oag.models.user_request import UserRequest as UserRequest
from chris_oag.models.workflow import Workflow as Workflow
from chris_oag.models.workflow_request import WorkflowRequest as WorkflowRequest

