//! Models for [ChRIS backend](https://github.com/FNNDSC/ChRIS_ultron_backEnd)
//! generated by [OpenAPI Generator](https://openapi-generator.tech).

#![allow(unused_imports)]
#![allow(clippy::too_many_arguments)]
pub mod models;
