# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a1
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PacsQueryStatus(str, Enum):
    """
    * `created` - Default initial * `sent` - Sent to PACS * `succeeded` - Finished successfully * `errored` - Finished with error
    """

    """
    allowed enum values
    """
    CREATED = 'created'
    SENT = 'sent'
    SUCCEEDED = 'succeeded'
    ERRORED = 'errored'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PacsQueryStatus from a JSON string"""
        return cls(json.loads(json_str))


