# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: 7.0.0-a1
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from aiochris_oag.models.pacs_query_status import PacsQueryStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PACSQuery(BaseModel):
    """
    PACSQuery
    """ # noqa: E501
    url: StrictStr
    id: StrictInt
    creation_date: datetime
    title: Optional[Annotated[str, Field(strict=True, max_length=300)]] = None
    query: Optional[Any] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=700)]] = None
    status: PacsQueryStatus
    pacs_identifier: StrictStr
    owner_username: StrictStr = Field(description="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.")
    execute: Optional[StrictBool] = True
    result: StrictStr
    retrieve_list: StrictStr
    __properties: ClassVar[List[str]] = ["url", "id", "creation_date", "title", "query", "description", "status", "pacs_identifier", "owner_username", "execute", "result", "retrieve_list"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PACSQuery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "url",
            "id",
            "creation_date",
            "status",
            "pacs_identifier",
            "owner_username",
            "result",
            "retrieve_list",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if query (nullable) is None
        # and model_fields_set contains the field
        if self.query is None and "query" in self.model_fields_set:
            _dict['query'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PACSQuery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "id": obj.get("id"),
            "creation_date": obj.get("creation_date"),
            "title": obj.get("title"),
            "query": obj.get("query"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "pacs_identifier": obj.get("pacs_identifier"),
            "owner_username": obj.get("owner_username"),
            "execute": obj.get("execute") if obj.get("execute") is not None else True,
            "result": obj.get("result"),
            "retrieve_list": obj.get("retrieve_list")
        })
        return _obj


