/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoolParameter {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "param_name")]
    pub param_name: String,
    #[serde(rename = "value")]
    pub value: bool,
    #[serde(rename = "type")]
    pub r#type: models::PluginParameterType,
    #[serde(rename = "plugin_inst")]
    pub plugin_inst: String,
    #[serde(rename = "plugin_param")]
    pub plugin_param: String,
}

impl BoolParameter {
    pub fn new(url: String, id: i32, param_name: String, value: bool, r#type: models::PluginParameterType, plugin_inst: String, plugin_param: String) -> BoolParameter {
        BoolParameter {
            url,
            id,
            param_name,
            value,
            r#type,
            plugin_inst,
            plugin_param,
        }
    }
}

