/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputeResource {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "modification_date")]
    pub modification_date: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "compute_url")]
    pub compute_url: String,
    #[serde(rename = "compute_auth_url", skip_serializing_if = "Option::is_none")]
    pub compute_auth_url: Option<String>,
    #[serde(rename = "compute_innetwork", skip_serializing_if = "Option::is_none")]
    pub compute_innetwork: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "max_job_exec_seconds", skip_serializing_if = "Option::is_none")]
    pub max_job_exec_seconds: Option<i32>,
}

impl ComputeResource {
    pub fn new(url: String, id: i32, creation_date: String, modification_date: String, name: String, compute_url: String) -> ComputeResource {
        ComputeResource {
            url,
            id,
            creation_date,
            modification_date,
            name,
            compute_url,
            compute_auth_url: None,
            compute_innetwork: None,
            description: None,
            max_job_exec_seconds: None,
        }
    }
}

