/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeedGroupPermission {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "feed_id")]
    pub feed_id: i32,
    #[serde(rename = "feed_name")]
    pub feed_name: String,
    #[serde(rename = "group_id")]
    pub group_id: i32,
    #[serde(rename = "group_name")]
    pub group_name: String,
    #[serde(rename = "feed")]
    pub feed: String,
    #[serde(rename = "group")]
    pub group: String,
}

impl FeedGroupPermission {
    pub fn new(url: String, id: i32, feed_id: i32, feed_name: String, group_id: i32, group_name: String, feed: String, group: String) -> FeedGroupPermission {
        FeedGroupPermission {
            url,
            id,
            feed_id,
            feed_name,
            group_id,
            group_name,
            feed,
            group,
        }
    }
}

