/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeedGroupPermissionRequest {
    #[serde(rename = "grp_name")]
    pub grp_name: String,
}

impl FeedGroupPermissionRequest {
    pub fn new(grp_name: String) -> FeedGroupPermissionRequest {
        FeedGroupPermissionRequest {
            grp_name,
        }
    }
}

