/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeedUserPermission {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "feed_id")]
    pub feed_id: i32,
    #[serde(rename = "feed_name")]
    pub feed_name: String,
    #[serde(rename = "user_id")]
    pub user_id: i32,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "user_username")]
    pub user_username: String,
    #[serde(rename = "feed")]
    pub feed: String,
    #[serde(rename = "user")]
    pub user: String,
}

impl FeedUserPermission {
    pub fn new(url: String, id: i32, feed_id: i32, feed_name: String, user_id: i32, user_username: String, feed: String, user: String) -> FeedUserPermission {
        FeedUserPermission {
            url,
            id,
            feed_id,
            feed_name,
            user_id,
            user_username,
            feed,
            user,
        }
    }
}

