/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileBrowserFileUserPermission {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<models::PermissionEnum>,
    #[serde(rename = "file_id")]
    pub file_id: i32,
    #[serde(rename = "file_fname")]
    pub file_fname: String,
    #[serde(rename = "user_id")]
    pub user_id: i32,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "user_username")]
    pub user_username: String,
    #[serde(rename = "file")]
    pub file: String,
    #[serde(rename = "user")]
    pub user: String,
}

impl FileBrowserFileUserPermission {
    pub fn new(url: String, id: i32, file_id: i32, file_fname: String, user_id: i32, user_username: String, file: String, user: String) -> FileBrowserFileUserPermission {
        FileBrowserFileUserPermission {
            url,
            id,
            permission: None,
            file_id,
            file_fname,
            user_id,
            user_username,
            file,
            user,
        }
    }
}

