/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileBrowserLinkFile : A superclass for serializers of ``ChrisFile`` or similar.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileBrowserLinkFile {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "fname", skip_serializing_if = "Option::is_none")]
    pub fname: Option<String>,
    /// Get the size of the file in bytes.
    #[serde(rename = "fsize")]
    pub fsize: i32,
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "owner_username")]
    pub owner_username: String,
    /// Custom method to get the hyperlink to the actual file resource.
    #[serde(rename = "file_resource")]
    pub file_resource: String,
    /// Custom method to get the hyperlink to the linked folder if the ChRIS link points to a folder.
    #[serde(rename = "linked_folder")]
    pub linked_folder: String,
    /// Custom method to get the hyperlink to the linked file if the ChRIS link points to a file.
    #[serde(rename = "linked_file")]
    pub linked_file: String,
    #[serde(rename = "parent_folder")]
    pub parent_folder: String,
    #[serde(rename = "group_permissions")]
    pub group_permissions: String,
    #[serde(rename = "user_permissions")]
    pub user_permissions: String,
    #[serde(rename = "owner")]
    pub owner: String,
}

impl FileBrowserLinkFile {
    /// A superclass for serializers of ``ChrisFile`` or similar.
    pub fn new(url: String, id: i32, creation_date: String, fsize: i32, owner_username: String, file_resource: String, linked_folder: String, linked_file: String, parent_folder: String, group_permissions: String, user_permissions: String, owner: String) -> FileBrowserLinkFile {
        FileBrowserLinkFile {
            url,
            id,
            creation_date,
            path: None,
            fname: None,
            fsize,
            public: None,
            owner_username,
            file_resource,
            linked_folder,
            linked_file,
            parent_folder,
            group_permissions,
            user_permissions,
            owner,
        }
    }
}

