/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileBrowserFolderGroupPermission {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<models::PermissionEnum>,
    #[serde(rename = "folder_id")]
    pub folder_id: i32,
    #[serde(rename = "folder_path")]
    pub folder_path: String,
    #[serde(rename = "group_id")]
    pub group_id: i32,
    #[serde(rename = "group_name")]
    pub group_name: String,
    #[serde(rename = "folder")]
    pub folder: String,
    #[serde(rename = "group")]
    pub group: String,
}

impl FileBrowserFolderGroupPermission {
    pub fn new(url: String, id: i32, folder_id: i32, folder_path: String, group_id: i32, group_name: String, folder: String, group: String) -> FileBrowserFolderGroupPermission {
        FileBrowserFolderGroupPermission {
            url,
            id,
            permission: None,
            folder_id,
            folder_path,
            group_id,
            group_name,
            folder,
            group,
        }
    }
}

