/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileBrowserFileGroupPermissionRequest {
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<models::PermissionEnum>,
    #[serde(rename = "grp_name", skip_serializing_if = "Option::is_none")]
    pub grp_name: Option<String>,
}

impl FileBrowserFileGroupPermissionRequest {
    pub fn new() -> FileBrowserFileGroupPermissionRequest {
        FileBrowserFileGroupPermissionRequest {
            permission: None,
            grp_name: None,
        }
    }
}

