/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileBrowserFolder {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "owner_username")]
    pub owner_username: String,
    #[serde(rename = "parent")]
    pub parent: String,
    #[serde(rename = "children")]
    pub children: String,
    #[serde(rename = "files")]
    pub files: String,
    #[serde(rename = "link_files")]
    pub link_files: String,
    #[serde(rename = "group_permissions")]
    pub group_permissions: String,
    #[serde(rename = "user_permissions")]
    pub user_permissions: String,
    #[serde(rename = "owner")]
    pub owner: String,
}

impl FileBrowserFolder {
    pub fn new(url: String, id: i32, creation_date: String, owner_username: String, parent: String, children: String, files: String, link_files: String, group_permissions: String, user_permissions: String, owner: String) -> FileBrowserFolder {
        FileBrowserFolder {
            url,
            id,
            creation_date,
            path: None,
            public: None,
            owner_username,
            parent,
            children,
            files,
            link_files,
            group_permissions,
            user_permissions,
            owner,
        }
    }
}

