/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileBrowserFileRequest : A superclass for serializers of ``ChrisFile`` or similar.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileBrowserFileRequest {
    #[serde(rename = "fname", skip_serializing_if = "Option::is_none")]
    pub fname: Option<std::path::PathBuf>,
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    #[serde(rename = "new_file_path", skip_serializing_if = "Option::is_none")]
    pub new_file_path: Option<String>,
}

impl FileBrowserFileRequest {
    /// A superclass for serializers of ``ChrisFile`` or similar.
    pub fn new() -> FileBrowserFileRequest {
        FileBrowserFileRequest {
            fname: None,
            public: None,
            new_file_path: None,
        }
    }
}

