/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileBrowserLinkFileGroupPermission {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<models::PermissionEnum>,
    #[serde(rename = "link_file_id")]
    pub link_file_id: i32,
    #[serde(rename = "link_file_fname")]
    pub link_file_fname: String,
    #[serde(rename = "group_id")]
    pub group_id: i32,
    #[serde(rename = "group_name")]
    pub group_name: String,
    #[serde(rename = "link_file")]
    pub link_file: String,
    #[serde(rename = "group")]
    pub group: String,
}

impl FileBrowserLinkFileGroupPermission {
    pub fn new(url: String, id: i32, link_file_id: i32, link_file_fname: String, group_id: i32, group_name: String, link_file: String, group: String) -> FileBrowserLinkFileGroupPermission {
        FileBrowserLinkFileGroupPermission {
            url,
            id,
            permission: None,
            link_file_id,
            link_file_fname,
            group_id,
            group_name,
            link_file,
            group,
        }
    }
}

