/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileBrowserFolderUserPermission {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<models::PermissionEnum>,
    #[serde(rename = "folder_id")]
    pub folder_id: i32,
    #[serde(rename = "folder_path")]
    pub folder_path: String,
    #[serde(rename = "user_id")]
    pub user_id: i32,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "user_username")]
    pub user_username: String,
    #[serde(rename = "folder")]
    pub folder: String,
    #[serde(rename = "user")]
    pub user: String,
}

impl FileBrowserFolderUserPermission {
    pub fn new(url: String, id: i32, folder_id: i32, folder_path: String, user_id: i32, user_username: String, folder: String, user: String) -> FileBrowserFolderUserPermission {
        FileBrowserFolderUserPermission {
            url,
            id,
            permission: None,
            folder_id,
            folder_path,
            user_id,
            user_username,
            folder,
            user,
        }
    }
}

