/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FtypeEnum : * `yaml` - YAML file * `json` - JSON file
/// * `yaml` - YAML file * `json` - JSON file
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FtypeEnum {
    #[serde(rename = "yaml")]
    Yaml,
    #[serde(rename = "json")]
    Json,

}

impl std::fmt::Display for FtypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Yaml => write!(f, "yaml"),
            Self::Json => write!(f, "json"),
        }
    }
}

impl Default for FtypeEnum {
    fn default() -> FtypeEnum {
        Self::Yaml
    }
}

