/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GenericDefaultPipingParameterValue : Overriden to get the default parameter value regardless of its type.
/// Overriden to get the default parameter value regardless of its type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GenericDefaultPipingParameterValue {
    String(String),
    Integer(i32),
    Number(f64),
    Boolean(bool),
}

impl Default for GenericDefaultPipingParameterValue {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

