/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenericDefaultPipingParameter {
    /// Custom method to get the correct url for the serialized object regardless of its type.
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "value")]
    pub value: Box<models::GenericDefaultPipingParameterValue>,
    #[serde(rename = "type")]
    pub r#type: models::PluginParameterType,
    #[serde(rename = "plugin_piping_id")]
    pub plugin_piping_id: i32,
    #[serde(rename = "plugin_piping_title")]
    pub plugin_piping_title: String,
    #[serde(rename = "previous_plugin_piping_id")]
    pub previous_plugin_piping_id: i32,
    #[serde(rename = "param_name")]
    pub param_name: String,
    #[serde(rename = "param_id")]
    pub param_id: i32,
    #[serde(rename = "plugin_piping")]
    pub plugin_piping: String,
    #[serde(rename = "plugin_name")]
    pub plugin_name: String,
    #[serde(rename = "plugin_version")]
    pub plugin_version: String,
    #[serde(rename = "plugin_id")]
    pub plugin_id: i32,
    #[serde(rename = "plugin_param")]
    pub plugin_param: String,
}

impl GenericDefaultPipingParameter {
    pub fn new(url: String, id: i32, value: models::GenericDefaultPipingParameterValue, r#type: models::PluginParameterType, plugin_piping_id: i32, plugin_piping_title: String, previous_plugin_piping_id: i32, param_name: String, param_id: i32, plugin_piping: String, plugin_name: String, plugin_version: String, plugin_id: i32, plugin_param: String) -> GenericDefaultPipingParameter {
        GenericDefaultPipingParameter {
            url,
            id,
            value: Box::new(value),
            r#type,
            plugin_piping_id,
            plugin_piping_title,
            previous_plugin_piping_id,
            param_name,
            param_id,
            plugin_piping,
            plugin_name,
            plugin_version,
            plugin_id,
            plugin_param,
        }
    }
}

