/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupUser {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "group_id")]
    pub group_id: i32,
    #[serde(rename = "group_name")]
    pub group_name: String,
    #[serde(rename = "user_id")]
    pub user_id: i32,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "user_username")]
    pub user_username: String,
    #[serde(rename = "user_email")]
    pub user_email: String,
    #[serde(rename = "group")]
    pub group: String,
    #[serde(rename = "user")]
    pub user: String,
}

impl GroupUser {
    pub fn new(url: String, id: i32, group_id: i32, group_name: String, user_id: i32, user_username: String, user_email: String, group: String, user: String) -> GroupUser {
        GroupUser {
            url,
            id,
            group_id,
            group_name,
            user_id,
            user_username,
            user_email,
            group,
            user,
        }
    }
}

