/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Note {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "feed")]
    pub feed: String,
}

impl Note {
    pub fn new(url: String, id: i32, feed: String) -> Note {
        Note {
            url,
            id,
            title: None,
            content: None,
            feed,
        }
    }
}

