/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PacsSeries {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "folder_path")]
    pub folder_path: String,
    #[serde(rename = "PatientID")]
    pub patient_id: String,
    #[serde(rename = "PatientName", skip_serializing_if = "Option::is_none")]
    pub patient_name: Option<String>,
    #[serde(rename = "PatientBirthDate", skip_serializing_if = "Option::is_none")]
    pub patient_birth_date: Option<String>,
    #[serde(rename = "PatientAge", skip_serializing_if = "Option::is_none")]
    pub patient_age: Option<i32>,
    #[serde(rename = "PatientSex", skip_serializing_if = "Option::is_none")]
    pub patient_sex: Option<Box<models::PacsSeriesPatientSex>>,
    #[serde(rename = "StudyDate")]
    pub study_date: String,
    #[serde(rename = "AccessionNumber", skip_serializing_if = "Option::is_none")]
    pub accession_number: Option<String>,
    #[serde(rename = "Modality", skip_serializing_if = "Option::is_none")]
    pub modality: Option<String>,
    #[serde(rename = "ProtocolName", skip_serializing_if = "Option::is_none")]
    pub protocol_name: Option<String>,
    #[serde(rename = "StudyInstanceUID")]
    pub study_instance_uid: String,
    #[serde(rename = "StudyDescription", skip_serializing_if = "Option::is_none")]
    pub study_description: Option<String>,
    #[serde(rename = "SeriesInstanceUID")]
    pub series_instance_uid: String,
    #[serde(rename = "SeriesDescription", skip_serializing_if = "Option::is_none")]
    pub series_description: Option<String>,
    #[serde(rename = "pacs_identifier")]
    pub pacs_identifier: String,
    #[serde(rename = "folder")]
    pub folder: String,
}

impl PacsSeries {
    pub fn new(url: String, id: i32, creation_date: String, folder_path: String, patient_id: String, study_date: String, study_instance_uid: String, series_instance_uid: String, pacs_identifier: String, folder: String) -> PacsSeries {
        PacsSeries {
            url,
            id,
            creation_date,
            folder_path,
            patient_id,
            patient_name: None,
            patient_birth_date: None,
            patient_age: None,
            patient_sex: None,
            study_date,
            accession_number: None,
            modality: None,
            protocol_name: None,
            study_instance_uid,
            study_description: None,
            series_instance_uid,
            series_description: None,
            pacs_identifier,
            folder,
        }
    }
}

