/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pacs {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "folder_path")]
    pub folder_path: String,
    #[serde(rename = "folder")]
    pub folder: String,
    #[serde(rename = "query_list")]
    pub query_list: String,
    #[serde(rename = "series_list")]
    pub series_list: String,
}

impl Pacs {
    pub fn new(url: String, id: i32, identifier: String, folder_path: String, folder: String, query_list: String, series_list: String) -> Pacs {
        Pacs {
            url,
            id,
            identifier,
            active: None,
            folder_path,
            folder,
            query_list,
            series_list,
        }
    }
}

