/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PacsQuery {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "query", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub query: Option<Option<serde_json::Value>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "status")]
    pub status: models::StatusEc0Enum,
    #[serde(rename = "pacs_identifier")]
    pub pacs_identifier: String,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "owner_username")]
    pub owner_username: String,
    #[serde(rename = "result")]
    pub result: String,
    #[serde(rename = "retrieve_list")]
    pub retrieve_list: String,
}

impl PacsQuery {
    pub fn new(url: String, id: i32, creation_date: String, title: String, status: models::StatusEc0Enum, pacs_identifier: String, owner_username: String, result: String, retrieve_list: String) -> PacsQuery {
        PacsQuery {
            url,
            id,
            creation_date,
            title,
            query: None,
            description: None,
            status,
            pacs_identifier,
            owner_username,
            result,
            retrieve_list,
        }
    }
}

