/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PacsRetrieve {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "pacs_query_id")]
    pub pacs_query_id: i32,
    #[serde(rename = "pacs_query_title")]
    pub pacs_query_title: String,
    #[serde(rename = "query", deserialize_with = "Option::deserialize")]
    pub query: Option<serde_json::Value>,
    #[serde(rename = "pacs_identifier")]
    pub pacs_identifier: String,
    #[serde(rename = "status")]
    pub status: models::StatusEc0Enum,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "owner_username")]
    pub owner_username: String,
    #[serde(rename = "result")]
    pub result: String,
    #[serde(rename = "pacs_query")]
    pub pacs_query: String,
}

impl PacsRetrieve {
    pub fn new(url: String, id: i32, creation_date: String, pacs_query_id: i32, pacs_query_title: String, query: Option<serde_json::Value>, pacs_identifier: String, status: models::StatusEc0Enum, owner_username: String, result: String, pacs_query: String) -> PacsRetrieve {
        PacsRetrieve {
            url,
            id,
            creation_date,
            pacs_query_id,
            pacs_query_title,
            query,
            pacs_identifier,
            status,
            owner_username,
            result,
            pacs_query,
        }
    }
}

