/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PacsFile : A superclass for serializers of ``ChrisFile`` or similar.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PacsFile {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "fname")]
    pub fname: String,
    /// Get the size of the file in bytes.
    #[serde(rename = "fsize")]
    pub fsize: i32,
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "owner_username")]
    pub owner_username: String,
    /// Custom method to get the hyperlink to the actual file resource.
    #[serde(rename = "file_resource")]
    pub file_resource: String,
    #[serde(rename = "parent_folder")]
    pub parent_folder: String,
    #[serde(rename = "owner")]
    pub owner: String,
}

impl PacsFile {
    /// A superclass for serializers of ``ChrisFile`` or similar.
    pub fn new(url: String, id: i32, creation_date: String, fname: String, fsize: i32, owner_username: String, file_resource: String, parent_folder: String, owner: String) -> PacsFile {
        PacsFile {
            url,
            id,
            creation_date,
            fname,
            fsize,
            public: None,
            owner_username,
            file_resource,
            parent_folder,
            owner,
        }
    }
}

