/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatientSexEnum : * `M` - Male * `F` - Female * `O` - Other
/// * `M` - Male * `F` - Female * `O` - Other
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PatientSexEnum {
    #[serde(rename = "M")]
    M,
    #[serde(rename = "F")]
    F,
    #[serde(rename = "O")]
    O,

}

impl std::fmt::Display for PatientSexEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::M => write!(f, "M"),
            Self::F => write!(f, "F"),
            Self::O => write!(f, "O"),
        }
    }
}

impl Default for PatientSexEnum {
    fn default() -> PatientSexEnum {
        Self::M
    }
}

