/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PermissionEnum : * `r` - Read * `w` - Write
/// * `r` - Read * `w` - Write
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PermissionEnum {
    #[serde(rename = "r")]
    R,
    #[serde(rename = "w")]
    W,

}

impl std::fmt::Display for PermissionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::R => write!(f, "r"),
            Self::W => write!(f, "w"),
        }
    }
}

impl Default for PermissionEnum {
    fn default() -> PermissionEnum {
        Self::R
    }
}

