/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PipelineSourceFileRequest : A superclass for serializers of ``ChrisFile`` or similar.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineSourceFileRequest {
    #[serde(rename = "fname")]
    pub fname: std::path::PathBuf,
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl PipelineSourceFileRequest {
    /// A superclass for serializers of ``ChrisFile`` or similar.
    pub fn new(fname: std::path::PathBuf) -> PipelineSourceFileRequest {
        PipelineSourceFileRequest {
            fname,
            public: None,
            r#type: None,
        }
    }
}

