/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pipeline {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    #[serde(rename = "authors", skip_serializing_if = "Option::is_none")]
    pub authors: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "owner_username")]
    pub owner_username: String,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "modification_date")]
    pub modification_date: String,
    #[serde(rename = "plugins")]
    pub plugins: String,
    #[serde(rename = "plugin_pipings")]
    pub plugin_pipings: String,
    #[serde(rename = "default_parameters")]
    pub default_parameters: String,
    #[serde(rename = "workflows")]
    pub workflows: String,
    #[serde(rename = "json_repr")]
    pub json_repr: String,
}

impl Pipeline {
    pub fn new(url: String, id: i32, owner_username: String, creation_date: String, modification_date: String, plugins: String, plugin_pipings: String, default_parameters: String, workflows: String, json_repr: String) -> Pipeline {
        Pipeline {
            url,
            id,
            name: None,
            locked: None,
            authors: None,
            category: None,
            description: None,
            owner_username,
            creation_date,
            modification_date,
            plugins,
            plugin_pipings,
            default_parameters,
            workflows,
            json_repr,
        }
    }
}

