/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelineCustomJson {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    #[serde(rename = "authors", skip_serializing_if = "Option::is_none")]
    pub authors: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Overriden to get the plugin_tree JSON string.
    #[serde(rename = "plugin_tree")]
    pub plugin_tree: String,
}

impl PipelineCustomJson {
    pub fn new(url: String, name: String, plugin_tree: String) -> PipelineCustomJson {
        PipelineCustomJson {
            url,
            name,
            locked: None,
            authors: None,
            category: None,
            description: None,
            plugin_tree,
        }
    }
}

