/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginInstance {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "previous_id")]
    pub previous_id: i32,
    #[serde(rename = "compute_resource_name", skip_serializing_if = "Option::is_none")]
    pub compute_resource_name: Option<String>,
    #[serde(rename = "plugin_id")]
    pub plugin_id: i32,
    #[serde(rename = "plugin_name")]
    pub plugin_name: String,
    #[serde(rename = "plugin_version")]
    pub plugin_version: String,
    #[serde(rename = "plugin_type")]
    pub plugin_type: models::PluginType,
    #[serde(rename = "feed_id")]
    pub feed_id: i32,
    #[serde(rename = "start_date")]
    pub start_date: String,
    #[serde(rename = "end_date")]
    pub end_date: String,
    #[serde(rename = "output_path")]
    pub output_path: String,
    #[serde(rename = "status")]
    pub status: models::PluginInstanceStatusEnum,
    #[serde(rename = "pipeline_id")]
    pub pipeline_id: i32,
    #[serde(rename = "pipeline_name")]
    pub pipeline_name: String,
    #[serde(rename = "workflow_id")]
    pub workflow_id: i32,
    #[serde(rename = "summary")]
    pub summary: String,
    #[serde(rename = "raw")]
    pub raw: String,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "owner_username")]
    pub owner_username: String,
    #[serde(rename = "cpu_limit", skip_serializing_if = "Option::is_none")]
    pub cpu_limit: Option<i32>,
    #[serde(rename = "memory_limit", skip_serializing_if = "Option::is_none")]
    pub memory_limit: Option<i32>,
    #[serde(rename = "number_of_workers", skip_serializing_if = "Option::is_none")]
    pub number_of_workers: Option<i32>,
    #[serde(rename = "gpu_limit", skip_serializing_if = "Option::is_none")]
    pub gpu_limit: Option<i32>,
    #[serde(rename = "size")]
    pub size: i64,
    #[serde(rename = "error_code")]
    pub error_code: String,
    #[serde(rename = "output_folder")]
    pub output_folder: String,
    #[serde(rename = "previous")]
    pub previous: String,
    #[serde(rename = "feed")]
    pub feed: String,
    #[serde(rename = "plugin")]
    pub plugin: String,
    #[serde(rename = "workflow")]
    pub workflow: String,
    #[serde(rename = "compute_resource")]
    pub compute_resource: String,
    #[serde(rename = "descendants")]
    pub descendants: String,
    #[serde(rename = "parameters")]
    pub parameters: String,
    #[serde(rename = "splits")]
    pub splits: String,
}

impl PluginInstance {
    pub fn new(url: String, id: i32, previous_id: i32, plugin_id: i32, plugin_name: String, plugin_version: String, plugin_type: models::PluginType, feed_id: i32, start_date: String, end_date: String, output_path: String, status: models::PluginInstanceStatusEnum, pipeline_id: i32, pipeline_name: String, workflow_id: i32, summary: String, raw: String, owner_username: String, size: i64, error_code: String, output_folder: String, previous: String, feed: String, plugin: String, workflow: String, compute_resource: String, descendants: String, parameters: String, splits: String) -> PluginInstance {
        PluginInstance {
            url,
            id,
            title: None,
            previous_id,
            compute_resource_name: None,
            plugin_id,
            plugin_name,
            plugin_version,
            plugin_type,
            feed_id,
            start_date,
            end_date,
            output_path,
            status,
            pipeline_id,
            pipeline_name,
            workflow_id,
            summary,
            raw,
            owner_username,
            cpu_limit: None,
            memory_limit: None,
            number_of_workers: None,
            gpu_limit: None,
            size,
            error_code,
            output_folder,
            previous,
            feed,
            plugin,
            workflow,
            compute_resource,
            descendants,
            parameters,
            splits,
        }
    }
}

