/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginInstanceSplitRequest {
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,
    #[serde(rename = "compute_resource_name", skip_serializing_if = "Option::is_none")]
    pub compute_resource_name: Option<String>,
}

impl PluginInstanceSplitRequest {
    pub fn new() -> PluginInstanceSplitRequest {
        PluginInstanceSplitRequest {
            filter: None,
            compute_resource_name: None,
        }
    }
}

