/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginInstanceSplit {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,
    #[serde(rename = "plugin_inst_id")]
    pub plugin_inst_id: i32,
    #[serde(rename = "created_plugin_inst_ids")]
    pub created_plugin_inst_ids: String,
    #[serde(rename = "plugin_inst")]
    pub plugin_inst: String,
}

impl PluginInstanceSplit {
    pub fn new(url: String, id: i32, creation_date: String, plugin_inst_id: i32, created_plugin_inst_ids: String, plugin_inst: String) -> PluginInstanceSplit {
        PluginInstanceSplit {
            url,
            id,
            creation_date,
            filter: None,
            plugin_inst_id,
            created_plugin_inst_ids,
            plugin_inst,
        }
    }
}

