/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginParameter {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::PluginParameterType>,
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    #[serde(rename = "default")]
    pub default: Box<models::PluginParameterDefault>,
    #[serde(rename = "flag")]
    pub flag: String,
    #[serde(rename = "short_flag", skip_serializing_if = "Option::is_none")]
    pub short_flag: Option<String>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(rename = "help", skip_serializing_if = "Option::is_none")]
    pub help: Option<String>,
    #[serde(rename = "ui_exposed", skip_serializing_if = "Option::is_none")]
    pub ui_exposed: Option<bool>,
    #[serde(rename = "plugin")]
    pub plugin: String,
}

impl PluginParameter {
    pub fn new(url: String, id: i32, name: String, default: models::PluginParameterDefault, flag: String, plugin: String) -> PluginParameter {
        PluginParameter {
            url,
            id,
            name,
            r#type: None,
            optional: None,
            default: Box::new(default),
            flag,
            short_flag: None,
            action: None,
            help: None,
            ui_exposed: None,
            plugin,
        }
    }
}

