/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PluginAdminRequest : A Plugin serializer for the PluginAdminList JSON view.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginAdminRequest {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "dock_image", skip_serializing_if = "Option::is_none")]
    pub dock_image: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "execshell", skip_serializing_if = "Option::is_none")]
    pub execshell: Option<String>,
    #[serde(rename = "selfpath", skip_serializing_if = "Option::is_none")]
    pub selfpath: Option<String>,
    #[serde(rename = "selfexec", skip_serializing_if = "Option::is_none")]
    pub selfexec: Option<String>,
    #[serde(rename = "min_number_of_workers", skip_serializing_if = "Option::is_none")]
    pub min_number_of_workers: Option<i32>,
    #[serde(rename = "max_number_of_workers", skip_serializing_if = "Option::is_none")]
    pub max_number_of_workers: Option<i32>,
    #[serde(rename = "min_cpu_limit", skip_serializing_if = "Option::is_none")]
    pub min_cpu_limit: Option<i32>,
    #[serde(rename = "max_cpu_limit", skip_serializing_if = "Option::is_none")]
    pub max_cpu_limit: Option<i32>,
    #[serde(rename = "min_memory_limit", skip_serializing_if = "Option::is_none")]
    pub min_memory_limit: Option<i32>,
    #[serde(rename = "max_memory_limit", skip_serializing_if = "Option::is_none")]
    pub max_memory_limit: Option<i32>,
    #[serde(rename = "min_gpu_limit", skip_serializing_if = "Option::is_none")]
    pub min_gpu_limit: Option<i32>,
    #[serde(rename = "max_gpu_limit", skip_serializing_if = "Option::is_none")]
    pub max_gpu_limit: Option<i32>,
    #[serde(rename = "fname", skip_serializing_if = "Option::is_none")]
    pub fname: Option<std::path::PathBuf>,
    #[serde(rename = "plugin_store_url", skip_serializing_if = "Option::is_none")]
    pub plugin_store_url: Option<String>,
    #[serde(rename = "compute_names")]
    pub compute_names: String,
}

impl PluginAdminRequest {
    /// A Plugin serializer for the PluginAdminList JSON view.
    pub fn new(compute_names: String) -> PluginAdminRequest {
        PluginAdminRequest {
            version: None,
            dock_image: None,
            description: None,
            execshell: None,
            selfpath: None,
            selfexec: None,
            min_number_of_workers: None,
            max_number_of_workers: None,
            min_cpu_limit: None,
            max_cpu_limit: None,
            min_memory_limit: None,
            max_memory_limit: None,
            min_gpu_limit: None,
            max_gpu_limit: None,
            fname: None,
            plugin_store_url: None,
            compute_names,
        }
    }
}

