/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PluginType : * `ds` - Data synthesis * `fs` - Feed synthesis * `ts` - Topology synthesis
/// * `ds` - Data synthesis * `fs` - Feed synthesis * `ts` - Topology synthesis
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PluginType {
    #[serde(rename = "ds")]
    Ds,
    #[serde(rename = "fs")]
    Fs,
    #[serde(rename = "ts")]
    Ts,

}

impl std::fmt::Display for PluginType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ds => write!(f, "ds"),
            Self::Fs => write!(f, "fs"),
            Self::Ts => write!(f, "ts"),
        }
    }
}

impl Default for PluginType {
    fn default() -> PluginType {
        Self::Ds
    }
}

