/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PluginInstanceStatusEnum : * `created` - Default initial * `waiting` - Waiting to be scheduled * `scheduled` - Scheduled on worker * `started` - Started on compute env * `registeringFiles` - Registering output files * `finishedSuccessfully` - Finished successfully * `finishedWithError` - Finished with error * `cancelled` - Cancelled
/// * `created` - Default initial * `waiting` - Waiting to be scheduled * `scheduled` - Scheduled on worker * `started` - Started on compute env * `registeringFiles` - Registering output files * `finishedSuccessfully` - Finished successfully * `finishedWithError` - Finished with error * `cancelled` - Cancelled
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PluginInstanceStatusEnum {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "waiting")]
    Waiting,
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "started")]
    Started,
    #[serde(rename = "registeringFiles")]
    RegisteringFiles,
    #[serde(rename = "finishedSuccessfully")]
    FinishedSuccessfully,
    #[serde(rename = "finishedWithError")]
    FinishedWithError,
    #[serde(rename = "cancelled")]
    Cancelled,

}

impl std::fmt::Display for PluginInstanceStatusEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Created => write!(f, "created"),
            Self::Waiting => write!(f, "waiting"),
            Self::Scheduled => write!(f, "scheduled"),
            Self::Started => write!(f, "started"),
            Self::RegisteringFiles => write!(f, "registeringFiles"),
            Self::FinishedSuccessfully => write!(f, "finishedSuccessfully"),
            Self::FinishedWithError => write!(f, "finishedWithError"),
            Self::Cancelled => write!(f, "cancelled"),
        }
    }
}

impl Default for PluginInstanceStatusEnum {
    fn default() -> PluginInstanceStatusEnum {
        Self::Created
    }
}

