/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PluginParameterType : * `string` - String values * `float` - Float values * `boolean` - Boolean values * `integer` - Integer values * `path` - Path values * `unextpath` - Unextracted path values
/// * `string` - String values * `float` - Float values * `boolean` - Boolean values * `integer` - Integer values * `path` - Path values * `unextpath` - Unextracted path values
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PluginParameterType {
    #[serde(rename = "string")]
    String,
    #[serde(rename = "float")]
    Float,
    #[serde(rename = "boolean")]
    Boolean,
    #[serde(rename = "integer")]
    Integer,
    #[serde(rename = "path")]
    Path,
    #[serde(rename = "unextpath")]
    Unextpath,

}

impl std::fmt::Display for PluginParameterType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::String => write!(f, "string"),
            Self::Float => write!(f, "float"),
            Self::Boolean => write!(f, "boolean"),
            Self::Integer => write!(f, "integer"),
            Self::Path => write!(f, "path"),
            Self::Unextpath => write!(f, "unextpath"),
        }
    }
}

impl Default for PluginParameterType {
    fn default() -> PluginParameterType {
        Self::String
    }
}

