/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginInstanceRequest<T> {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "compute_resource_name", skip_serializing_if = "Option::is_none")]
    pub compute_resource_name: Option<String>,
    #[serde(rename = "cpu_limit", skip_serializing_if = "Option::is_none")]
    pub cpu_limit: Option<i32>,
    #[serde(rename = "memory_limit", skip_serializing_if = "Option::is_none")]
    pub memory_limit: Option<i32>,
    #[serde(rename = "number_of_workers", skip_serializing_if = "Option::is_none")]
    pub number_of_workers: Option<i32>,
    #[serde(rename = "gpu_limit", skip_serializing_if = "Option::is_none")]
    pub gpu_limit: Option<i32>,
    #[serde(rename = "previous_id", skip_serializing_if = "Option::is_none")]
    pub previous_id: Option<i32>,

    /// Plugin parameters
    #[serde(flatten)]
    pub parameters: T,
}

impl<T> PluginInstanceRequest<T> {
    pub fn new(parameters: T) -> Self {
        PluginInstanceRequest {
            title: None,
            compute_resource_name: None,
            cpu_limit: None,
            memory_limit: None,
            number_of_workers: None,
            gpu_limit: None,
            previous_id: None,
            parameters,
        }
    }
}

