/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PluginAdmin : A Plugin serializer for the PluginAdminList JSON view.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginAdmin {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "dock_image", skip_serializing_if = "Option::is_none")]
    pub dock_image: Option<String>,
    #[serde(rename = "public_repo")]
    pub public_repo: String,
    #[serde(rename = "icon")]
    pub icon: String,
    #[serde(rename = "type")]
    pub r#type: models::PluginType,
    #[serde(rename = "stars")]
    pub stars: i32,
    #[serde(rename = "authors")]
    pub authors: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "category")]
    pub category: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "documentation")]
    pub documentation: String,
    #[serde(rename = "license")]
    pub license: String,
    #[serde(rename = "execshell", skip_serializing_if = "Option::is_none")]
    pub execshell: Option<String>,
    #[serde(rename = "selfpath", skip_serializing_if = "Option::is_none")]
    pub selfpath: Option<String>,
    #[serde(rename = "selfexec", skip_serializing_if = "Option::is_none")]
    pub selfexec: Option<String>,
    #[serde(rename = "min_number_of_workers", skip_serializing_if = "Option::is_none")]
    pub min_number_of_workers: Option<i32>,
    #[serde(rename = "max_number_of_workers", skip_serializing_if = "Option::is_none")]
    pub max_number_of_workers: Option<i32>,
    #[serde(rename = "min_cpu_limit", skip_serializing_if = "Option::is_none")]
    pub min_cpu_limit: Option<i32>,
    #[serde(rename = "max_cpu_limit", skip_serializing_if = "Option::is_none")]
    pub max_cpu_limit: Option<i32>,
    #[serde(rename = "min_memory_limit", skip_serializing_if = "Option::is_none")]
    pub min_memory_limit: Option<i32>,
    #[serde(rename = "max_memory_limit", skip_serializing_if = "Option::is_none")]
    pub max_memory_limit: Option<i32>,
    #[serde(rename = "min_gpu_limit", skip_serializing_if = "Option::is_none")]
    pub min_gpu_limit: Option<i32>,
    #[serde(rename = "max_gpu_limit", skip_serializing_if = "Option::is_none")]
    pub max_gpu_limit: Option<i32>,
    #[serde(rename = "meta")]
    pub meta: String,
    #[serde(rename = "parameters")]
    pub parameters: String,
    #[serde(rename = "instances")]
    pub instances: String,
    #[serde(rename = "compute_resources")]
    pub compute_resources: String,
}

impl PluginAdmin {
    /// A Plugin serializer for the PluginAdminList JSON view.
    pub fn new(url: String, id: i32, creation_date: String, name: String, public_repo: String, icon: String, r#type: models::PluginType, stars: i32, authors: String, title: String, category: String, documentation: String, license: String, meta: String, parameters: String, instances: String, compute_resources: String) -> PluginAdmin {
        PluginAdmin {
            url,
            id,
            creation_date,
            name,
            version: None,
            dock_image: None,
            public_repo,
            icon,
            r#type,
            stars,
            authors,
            title,
            category,
            description: None,
            documentation,
            license,
            execshell: None,
            selfpath: None,
            selfexec: None,
            min_number_of_workers: None,
            max_number_of_workers: None,
            min_cpu_limit: None,
            max_cpu_limit: None,
            min_memory_limit: None,
            max_memory_limit: None,
            min_gpu_limit: None,
            max_gpu_limit: None,
            meta,
            parameters,
            instances,
            compute_resources,
        }
    }
}

