/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginPiping {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "previous_id")]
    pub previous_id: i32,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "plugin_id")]
    pub plugin_id: i32,
    #[serde(rename = "plugin_name")]
    pub plugin_name: String,
    #[serde(rename = "plugin_version")]
    pub plugin_version: String,
    #[serde(rename = "pipeline_id")]
    pub pipeline_id: i32,
    #[serde(rename = "previous")]
    pub previous: String,
    #[serde(rename = "plugin")]
    pub plugin: String,
    #[serde(rename = "pipeline")]
    pub pipeline: String,
}

impl PluginPiping {
    pub fn new(url: String, id: i32, previous_id: i32, title: String, plugin_id: i32, plugin_name: String, plugin_version: String, pipeline_id: i32, previous: String, plugin: String, pipeline: String) -> PluginPiping {
        PluginPiping {
            url,
            id,
            previous_id,
            title,
            plugin_id,
            plugin_name,
            plugin_version,
            pipeline_id,
            previous,
            plugin,
            pipeline,
        }
    }
}

