/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginMeta {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "modification_date")]
    pub modification_date: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "stars", skip_serializing_if = "Option::is_none")]
    pub stars: Option<i32>,
    #[serde(rename = "public_repo", skip_serializing_if = "Option::is_none")]
    pub public_repo: Option<String>,
    #[serde(rename = "license", skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::PluginType>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "authors", skip_serializing_if = "Option::is_none")]
    pub authors: Option<String>,
    #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
    pub documentation: Option<String>,
    #[serde(rename = "plugins")]
    pub plugins: String,
}

impl PluginMeta {
    pub fn new(url: String, id: i32, creation_date: String, modification_date: String, name: String, plugins: String) -> PluginMeta {
        PluginMeta {
            url,
            id,
            creation_date,
            modification_date,
            name,
            title: None,
            stars: None,
            public_repo: None,
            license: None,
            r#type: None,
            icon: None,
            category: None,
            authors: None,
            documentation: None,
            plugins,
        }
    }
}

