/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusEc0Enum : * `created` - Default initial * `sent` - Sent to PACS * `succeeded` - Finished successfully * `errored` - Finished with error
/// * `created` - Default initial * `sent` - Sent to PACS * `succeeded` - Finished successfully * `errored` - Finished with error
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StatusEc0Enum {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "sent")]
    Sent,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "errored")]
    Errored,

}

impl std::fmt::Display for StatusEc0Enum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Created => write!(f, "created"),
            Self::Sent => write!(f, "sent"),
            Self::Succeeded => write!(f, "succeeded"),
            Self::Errored => write!(f, "errored"),
        }
    }
}

impl Default for StatusEc0Enum {
    fn default() -> StatusEc0Enum {
        Self::Created
    }
}

