/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tagging {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "tag_id")]
    pub tag_id: i32,
    #[serde(rename = "feed_id")]
    pub feed_id: i32,
    #[serde(rename = "tag")]
    pub tag: String,
    #[serde(rename = "feed")]
    pub feed: String,
}

impl Tagging {
    pub fn new(url: String, id: i32, tag_id: i32, feed_id: i32, tag: String, feed: String) -> Tagging {
        Tagging {
            url,
            id,
            tag_id,
            feed_id,
            tag,
            feed,
        }
    }
}

