/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "email")]
    pub email: String,
    /// Designates whether the user can log into this admin site.
    #[serde(rename = "is_staff", skip_serializing_if = "Option::is_none")]
    pub is_staff: Option<bool>,
    #[serde(rename = "groups")]
    pub groups: String,
}

impl User {
    pub fn new(url: String, id: i32, email: String, groups: String) -> User {
        User {
            url,
            id,
            username: None,
            email,
            is_staff: None,
            groups,
        }
    }
}

