/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowRequest {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "previous_plugin_inst_id", skip_serializing_if = "Option::is_none")]
    pub previous_plugin_inst_id: Option<u32>,
    #[serde(rename = "nodes_info", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nodes_info: Option<Option<serde_json::Value>>,
}

impl WorkflowRequest {
    pub fn new() -> WorkflowRequest {
        WorkflowRequest {
            title: None,
            previous_plugin_inst_id: None,
            nodes_info: None,
        }
    }
}

