/*
 * ChRIS Research Integration System: Ultron BackEnd (CUBE) API
 *
 * The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.
 *
 * The version of the OpenAPI document: 6.3.3
 * Contact: dev@babymri.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Workflow {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "creation_date")]
    pub creation_date: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "pipeline_id")]
    pub pipeline_id: i32,
    #[serde(rename = "pipeline_name")]
    pub pipeline_name: String,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "owner_username")]
    pub owner_username: String,
    /// Overriden to get the number of plugin instances in 'created' status.
    #[serde(rename = "created_jobs")]
    pub created_jobs: i32,
    /// Overriden to get the number of plugin instances in 'waiting' status.
    #[serde(rename = "waiting_jobs")]
    pub waiting_jobs: i32,
    /// Overriden to get the number of plugin instances in 'scheduled' status.
    #[serde(rename = "scheduled_jobs")]
    pub scheduled_jobs: i32,
    /// Overriden to get the number of plugin instances in 'started' status.
    #[serde(rename = "started_jobs")]
    pub started_jobs: i32,
    /// Overriden to get the number of plugin instances in 'registeringFiles' status.
    #[serde(rename = "registering_jobs")]
    pub registering_jobs: i32,
    /// Overriden to get the number of plugin instances in 'finishedSuccessfully' status.
    #[serde(rename = "finished_jobs")]
    pub finished_jobs: i32,
    /// Overriden to get the number of plugin instances in 'finishedWithError' status.
    #[serde(rename = "errored_jobs")]
    pub errored_jobs: i32,
    /// Overriden to get the number of plugin instances in 'cancelled' status.
    #[serde(rename = "cancelled_jobs")]
    pub cancelled_jobs: i32,
    #[serde(rename = "pipeline")]
    pub pipeline: String,
    #[serde(rename = "plugin_instances")]
    pub plugin_instances: String,
}

impl Workflow {
    pub fn new(url: String, id: i32, creation_date: String, pipeline_id: i32, pipeline_name: String, owner_username: String, created_jobs: i32, waiting_jobs: i32, scheduled_jobs: i32, started_jobs: i32, registering_jobs: i32, finished_jobs: i32, errored_jobs: i32, cancelled_jobs: i32, pipeline: String, plugin_instances: String) -> Workflow {
        Workflow {
            url,
            id,
            creation_date,
            title: None,
            pipeline_id,
            pipeline_name,
            owner_username,
            created_jobs,
            waiting_jobs,
            scheduled_jobs,
            started_jobs,
            registering_jobs,
            finished_jobs,
            errored_jobs,
            cancelled_jobs,
            pipeline,
            plugin_instances,
        }
    }
}

