'!include': 'common.yaml'

generatorName: typescript
outputDir: typescript-deno

# https://openapi-generator.tech/docs/generators/typescript/#config-options
additionalProperties:
  npmName: '@fnndsc/chris-oag-deno'
  framework: framework
  platform: deno
  nullSafeAdditionalProps: true
  paramNaming: camelCase
  '!include': version_npm.yaml

