'!include': 'common.yaml'

generatorName: typescript
outputDir: typescript-node

# https://openapi-generator.tech/docs/generators/typescript/#config-options
additionalProperties:
  npmName: '@fnndsc/chris-oag-node'
  framework: framework
  platform: node
  nullSafeAdditionalProps: true
  paramNaming: camelCase
  '!include': version_npm.yaml

